version: 2
updates:
  - package-ecosystem: "pip-compile" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    allow:
      - dependency-type: direct
    reviewers:
      - winfried-ripken
