# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# See
# https://medium.com/staqu-dev-logs/keeping-python-code-clean-with-pre-commit-hooks-black-flake8-and-isort-cac8b01e0ea1
default_language_version:
  python: python3.9
exclude: (?x)(^wandb| ^docs/_build)
repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black # Format Python code
        additional_dependencies: ["--index-url=https://pypi.org/simple/"]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.4 # Use the sha / tag you want to point at
    hooks:
      - id: autopep8
        additional_dependencies: ["--index-url=https://pypi.org/simple/"]
  - repo: https://github.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8 # Apply flake 8 python file linter
        additional_dependencies:
          - "--index-url=https://pypi.org/simple/"
          - "flake8-annotations==2.5.0"
          - "flake8-bugbear==21.9.2"
          - "flake8-docstrings==1.5.0"
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.27.1
    hooks:
      - id: yamllint # Check YAML Files
        args: ["-d", "{extends: relaxed, rules: {line-length: {max: 120 }}}"]
        additional_dependencies: ["--index-url=https://pypi.org/simple/"]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black-jupyter # Format jupyter notebooks
        additional_dependencies:
          [".[jupyter]", "--index-url=https://pypi.org/simple/"]
  - repo: https://github.com/s-weigand/flake8-nb
    rev: v0.4.0
    hooks:
      - id: flake8-nb # Lint jupyter notebooks
        additional_dependencies: ["--index-url=https://pypi.org/simple/"]
  - repo: https://github.com/pzdkn/mirror-nbstripout
    rev: 0.6.0
    hooks:
      - id: nbstripout
        additional_dependencies: ["--index-url=https://pypi.org/simple/"]
  - repo: https://github.com/python-poetry/poetry
    rev: 1.3.2
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: [--check]
      - id: poetry-export
        args: [-f, requirements.txt, -o, requirements.txt, --with=dev, --with=doc, -Eall]
